name: orama_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1
  intl: ^0.19.0
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  mobx_codegen: ^2.6.1
  logging: ^1.2.0
  http: ^1.2.0
  dio: ^5.4.3+1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  chips_choice: ^3.0.1
  connectivity_plus: ^6.0.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.1.0
  share_plus: ^7.2.1
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  assets:
    - lib/images/
    - shorebird.yaml
  uses-material-design: true