// sabores.dart

const Map<String, List<String>> sabores = {
  'Ao Leite': [
    'Baunilha, Paçoca e Doce de Leite',
    'Baunilha com Morango',
    'Flocos da Amazônia',
    'Cocada',
    'Doce de Leite Orama',
    'Café da Mantiqueira',
    'Paçoca',
    'Banana Caramelada',
    'Menta com Chocolate',
    'Bolo de Cenoura',
    'Cacau Bahia com Laranja',
    'Brigadeiro Meio Amargo',
    'Requeijão com Goiabada',
    'Milho Verde',
    'Mousse de Maracujá com Bolo',
    'Coco com Abóbora',
    'Brigadeiro com Cookies',
    'Tapioca',
    'Coco com doce de leite Crocante',
    'Camafeu com Nozes',
    'Passas ao Rum',
    'Chocolate com Pimenta',
    'Milho Cremoso Crocante',
  ],
  'Veganos': [
    'Açaí Juçara (Vegano)',
    'Maracujá e Mel (Vegano)',
    'Manga com Alecrim (Vegano)',
    'Morango com Hortelã (Vegano)',
    'Limão (Vegano)',
    'Cupuaçu (Vegano)',
    'Amora (Vegano)',
    'Uva (Vegano)',
    'Cajá (Vegano)',
    'Açaí da Amazônia (Vegano)',
    'Groselha (Vegano)',
    'Seriguela',
    'Tamarindo',
  ],
  'Massas': [
    'Baunilha',
    'Chocolate',
    'Manteiga',
  ],
  'Especiais': [
    'Baunilha com Mirtilo',
    'Espumante',
    'Torta de Maçã',
    'Bem Casados',
    'Brigadeiro com Whey',
    'Banana com Whey',
    'Caramelo com Whey',
    'Açaí Zero Açúcar',
    'Pitaya com Morango',
    'Chocolate Zero Açúcar',
    'Uva Vegano',
    'Limão Zero Açúcar',
    'Coco Verde Zero Açúcar',
    'Canjica com Canela',
    'Coco com Abobora',
    'Abacaxi ao Vinho',
    'Vinho Quente',
  ],
};
