// sabores.dart

const Map<String, List<String>> sabores = {
  'Ao Leite': [
    'Baunilha, Paçoca e Doce de Leite',
    'Baunilha com Morango',
    'Flocos da Amazônia',
    'Cocada',
    'Doce de Leite Orama',
    'Café da Mantiqueira',
    'Paçoca',
    'Banana Caramelada',
    'Menta com Chocolate',
    'Bolo de Cenoura',
    'Cacau Bahia com Laranja',
    'Brigadeiro Meio Amargo',
    'Requeijão com Goiabada',
    'Milho Verde',
    'Mousse de Maracujá com Bolo',
    'Coco com Abóbora',
    'Brigadeiro com Cookies',
    'Tapioca',
  ],
  'Veganos': [
    'Açaí Juçara (Vegano)',
    'Maracujá e Mel (Vegano)',
    'Manga com Alecrim (Vegano)',
    'Morango com Hortelã (Vegano)',
    'Limão (Vegano)',
    'Cupuaçu (Vegano)',
    'Amora (Vegano)',
    'Uva (Vegano)',
    'Cajá (Vegano)',
    'Açaí da Amazônia (Vegano)',
    'Groselha (Vegano)',
  ],
  'Zero Açúcar': [
    'Brigadeiro com Whey',
    'Banana com Whey',
    'Caramelo com Whey',
    'Açaí Vegano',
    'Pitaya com Morango',
    'Chocolate Vegano',
    'Uva Vegano',
    'Limão Vegano',
    'Coco Verde Vegano',
  ],
};
