// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeV8YndBfXMZO2roFR85d5x-QWB8qDxvk',
    appId: '1:263340861974:web:c15c1690a64abaf0a3a337',
    messagingSenderId: '263340861974',
    projectId: 'orama-checklist',
    authDomain: 'orama-checklist.firebaseapp.com',
    storageBucket: 'orama-checklist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2aya5rQSXo0D5yKtOer260WpPCw8A7Y',
    appId: '1:263340861974:android:02ab19d231698650a3a337',
    messagingSenderId: '263340861974',
    projectId: 'orama-checklist',
    storageBucket: 'orama-checklist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcqSpk1lizPM58PzrwbcWpCmCtvvhA0ls',
    appId: '1:263340861974:ios:68270b723826c7e9a3a337',
    messagingSenderId: '263340861974',
    projectId: 'orama-checklist',
    storageBucket: 'orama-checklist.appspot.com',
    iosBundleId: 'com.example.oramaUser',
  );
}
