name: Build and Deploy iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.17.0'
    - name: Install Shorebird CLI
      run: dart pub global activate shorebird
    - name: Authenticate Shorebird
      run: shorebird login
      env:
        SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }} # Adicione seu token do Shorebird aos secrets do GitHub
    - name: Build IPA
      run: shorebird build ios
    - name: Deploy to Shorebird
      run: shorebird deploy ios
