# Este arquivo foi gerado automaticamente pelo Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Passo 2: Instalar o Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Passo 3: Instalar dependências do Flutter
      - name: Install dependencies
        run: flutter pub get

      # Passo 4: Construir o app Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Passo 5: Fazer o deploy para o Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORAMA_CHECKLIST }}
          channelId: live
          projectId: orama-checklist
